"""Blueprints API — the kubectl get/apply deployment analogue for agent blueprint management."""
import re
from fastapi import APIRouter
from pydantic import BaseModel
from ..state import RuntimeState

router = APIRouter()

# In-memory registry for newly registered blueprints
_custom_blueprints: list[dict] = []


class GenerateBlueprintRequest(BaseModel):
    """Request to generate a blueprint YAML from a natural-language description."""

    description: str

    def __repr__(self) -> str:
        return f"GenerateBlueprintRequest(description={self.description[:40]!r})"


class RegisterBlueprintRequest(BaseModel):
    """Request to register a new blueprint — analogous to kubectl apply for a CRD."""

    name: str
    description: str
    tier: str = "capable"
    version: str = "1.0"
    capabilities: list[str] = []

    def __repr__(self) -> str:
        return f"RegisterBlueprintRequest(name={self.name!r}, tier={self.tier!r})"


def _generate_blueprint_yaml(description: str) -> str:
    """Generate deterministic blueprint YAML from a description.

    Extracts keywords to determine tier and capabilities without any LLM calls.
    Analogous to a Helm chart template render — purely deterministic.
    """
    desc_lower = description.lower()

    # Determine tier from keywords
    if any(kw in desc_lower for kw in ["complex", "best", "advanced", "reasoning", "deep", "research"]):
        tier = "best"
    elif any(kw in desc_lower for kw in ["code", "data", "analysis", "sql", "query", "debug"]):
        tier = "capable"
    else:
        tier = "fast"

    # Determine capabilities from keywords
    capabilities: list[str] = []
    if any(kw in desc_lower for kw in ["web", "search", "internet", "browse", "url", "http"]):
        capabilities.append("web_search")
    if any(kw in desc_lower for kw in ["code", "exec", "run", "script", "python"]):
        capabilities.append("code_exec")
    if any(kw in desc_lower for kw in ["file", "read", "write", "disk", "storage"]):
        capabilities.append("file_read")
    if any(kw in desc_lower for kw in ["database", "db", "sql", "query", "postgres"]):
        capabilities.append("db_query")
    if any(kw in desc_lower for kw in ["fetch", "url", "scrape", "crawl"]):
        capabilities.append("fetch_url")

    # Generate a slug name from the description
    words = re.findall(r"[a-z]+", desc_lower)
    stop_words = {"an", "a", "the", "for", "and", "or", "with", "that", "to", "of", "in", "on"}
    name_words = [w for w in words if w not in stop_words][:3]
    name = "_".join(name_words) + "_agent" if name_words else "custom_agent"

    caps_yaml = "\n".join(f"  - {c}" for c in capabilities) if capabilities else "  []"

    yaml_str = f"""# Generated by KubeAI Blueprint Generator
# Analogous to a Kubernetes Deployment manifest
apiVersion: kubeai/v1
kind: AgentBlueprint
metadata:
  name: {name}
  version: "1.0"
spec:
  description: "{description}"
  tier: {tier}
  capabilities:
{caps_yaml if capabilities else "  []"}
  system_prompt: |
    You are a specialized AI agent for: {description}
    Operate within KubeAI runtime constraints.
    Always be concise, accurate, and efficient.
  max_tokens: 2048
  resource_limits:
    max_concurrent_tasks: 5
    token_budget_per_task: 2048
    cost_limit_usd: 0.10
"""
    return yaml_str


@router.get("/blueprints")
def list_blueprints() -> list[dict]:
    """List all registered blueprints.

    Analogous to 'kubectl get deployments' — returns built-in and
    user-registered agent blueprints.
    """
    state = RuntimeState()
    return state.get_blueprints() + _custom_blueprints


@router.post("/blueprints/generate")
def generate_blueprint(body: GenerateBlueprintRequest) -> dict:
    """Generate a blueprint YAML from a natural-language description.

    Deterministic template generation — no LLM calls. Analogous to
    'helm template' rendering a chart from values without a cluster connection.
    """
    yaml_str = _generate_blueprint_yaml(body.description)
    return {"yaml": yaml_str, "description": body.description}


@router.post("/blueprints/register")
def register_blueprint(body: RegisterBlueprintRequest) -> dict:
    """Register a new custom blueprint.

    Analogous to 'kubectl apply -f blueprint.yaml' — adds the blueprint
    to the in-memory registry so it can be used for task routing.
    """
    blueprint = {
        "name": body.name,
        "description": body.description,
        "tier": body.tier,
        "version": body.version,
        "capabilities": body.capabilities,
    }
    _custom_blueprints.append(blueprint)
    return {"registered": True, "blueprint": blueprint}
